### ISSUE TITLE
web-frontend fails in lab 4.2

### ISSUE THREAD

**Issue by michael-staffa** [tetratelabs/cncf-istio-course#3]
Hello, the expected result for this is to see the web front end, but I receive the following NodeJS error:

> Error calling downstream service
ERR_UNESCAPED_CHARACTERS
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new NodeError (internal/errors.js:322:7)
    at new ClientRequest (_http_client.js:155:13)
    at Object.request (http.js:94:10)
    at RedirectableRequest._performRequest (/app/node_modules/follow-redirects/index.js:279:24)
    at new RedirectableRequest (/app/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/app/node_modules/follow-redirects/index.js:511:14)
    at dispatchHttpRequest (/app/node_modules/axios/lib/adapters/http.js:262:25)
    at new Promise (<anonymous>)
    at httpAdapter (/app/node_modules/axios/lib/adapters/http.js:49:10)
    at dispatchRequest (/app/node_modules/axios/lib/core/dispatchRequest.js:58:10)

Not sure if it's something I've done with my deployments or something wrong with the service.

**Comment by michael-staffa** [comment]
I'm now quite certain it's something wrong with the service. I tried to find where you were building this from, but could only find the container image on GCR. Please share the repo it comes from and I'll see if I can make a PR with a fix.

**Comment by ramanjk** [comment]
Hello, While I am trying this web-frontend and customer services deployments , pod's getting crashloopbackup with main container getting exec format error. 
Note: I am doing this on my Azure kubernetes cluster and nodes with aarch64 . 

So it seems to be image issue , could you please provide images for all testing deployments for istio labs with the support for aarch64.?
